### ISSUE TITLE
Add "DeFI" tag 

### ISSUE THREAD

**Issue by devcorn** [lovincyrus/cosmonauts-world#108]
I suggest we add "DeFi' tag

**Comment by lovincyrus** [comment]
@devcorn The tags can be interpreted as category, as seen: https://github.com/lovincyrus/cosmonauts-world/pull/79

e.g.: https://cosmonauts-world-git-category.lovincyrus.now.sh/projects/kava

![image](https://user-images.githubusercontent.com/1021101/82489672-e40c3a80-9a96-11ea-8121-3c31d900c1e6.png)

Just need some help to hash out the categories for each project then I can merge it. Feel free to contribute to this file by adding categories to each project.
https://github.com/lovincyrus/cosmonauts-world/blob/d7c8e6b7ef63b33473320d01796690d9780fb6f8/data/posts-manifest.js#L43
