### ISSUE TITLE
Add Oasis Labs

### ISSUE THREAD

**Issue by haymond** [lovincyrus/cosmonauts-world#5]
1. Team - [Oasis Labs](https://www.oasislabs.com/) 
2. Proof - Oasis Labs forked Tendermint on [their Github](https://github.com/oasislabs). Also Tendermint is mentioned on [page 1 of Ekiden](https://arxiv.org/pdf/1804.05141.pdf).

**Comment by lovincyrus** [comment]
Please provide the complete information as shown here: https://github.com/lovincyrus/cosmonauts-world/blob/master/data/posts.default.json @haymond

**Comment by lovincyrus** [comment]
Closed - as this project will begin with a clean slate https://github.com/lovincyrus/cosmonauts-world/issues/8
